name: Deploy Docusaurus to GitHub Pages
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify the Node.js version you are using

      - name: Install Dependencies
        run: npm ci # 'npm ci' is preferred for CI/CD as it is faster and more reliable

      - name: Build Docusaurus Site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # If you're deploying to the root of 'gh-pages' and want to keep the history, consider using 'keep_files: true'
          keep_files: true # Optional: Use if you're pushing to the same branch and want to keep existing files
